// frontend - next.js/app/not-found.tsx
export default function Custom404() {
  return (
    <div className="min-h-screen flex items-center justify-center flex-col px-4 text-center">
      <h1 className="text-4xl sm:text-6xl font-bold mb-4">404</h1>
      <p className="text-xl sm:text-3xl font-bold">
        Podanej strony nie znaleziono.
      </p>
    </div>
  );
}

// frontend - angular/src/app/not-found/not-found.component.ts
import { Component } from '@angular/core';
import { FooterComponent } from '../footer/footer.component';
import { HeaderComponent } from '../header/header.component';

@Component({
  selector: 'app-not-found',
  imports: [HeaderComponent, FooterComponent],
  templateUrl: './not-found.component.html',
  standalone: true,
})
export class NotFoundComponent {}

<main class="w-screen min-h-screen">
  <app-header />
  <div
    class="flex flex-col w-[90%] min-h-[75dvh] items-center justify-center space-y-10 text-black font-roboto font-bold text-3xl max-md:text-xl text-center mx-10"
  >
    <p>404</p>
    <p>
      Podanej strony nie znaleziono.
    </p>
  </div>
  <app-footer />
</main>
