// frontend - angular/src/app/add-photo/add-photo.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Observable } from 'rxjs';
import { PhotoService } from '../../services/photo.service';
import { FooterComponent } from '../footer/footer.component';
import { HeaderComponent } from '../header/header.component';
import { ImageComponent } from '../image/image.component';

@Component({
  selector: 'app-add-photo',
  imports: [HeaderComponent, FooterComponent, ImageComponent, CommonModule],
  templateUrl: './add-photo.component.html',
  standalone: true,
})
export class AddPhotoComponent {
  private selectedPhoto!: File;
  protected isUploading: boolean;
  protected previewUrl: string | null;
  protected isUploaded: boolean | null;

  constructor(private router: Router, private photoService: PhotoService) {
    this.isUploading = false;
    this.previewUrl = null;
    this.isUploaded = null;
  }

  public onDragOver(event: DragEvent): void {
    event.preventDefault();
  }

  public onDrop(event: DragEvent): void {
    event.preventDefault();
    if (event.dataTransfer && event.dataTransfer.files.length > 0) {
      this.selectedPhoto = event.dataTransfer.files[0];
      this.convertToBase64();
    }
  }

  public onFileSelected(event: Event): void {
    const input: HTMLInputElement = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.selectedPhoto = input.files[0];
      this.convertToBase64();
    }
  }

  private convertToBase64(): void {
    if (!this.selectedPhoto) {
      return;
    }
    const reader: FileReader = new FileReader();
    reader.onload = () => {
      this.previewUrl = reader.result as string;
      this.handleUploadPhoto();
    };
    reader.readAsDataURL(this.selectedPhoto);
  }

  private handleUploadPhoto(): void {
    if (this.previewUrl !== null) {
      this.isUploading = true;
      const isUploadedObservable: Observable<boolean> =
        this.photoService.handleUploadPhoto(this.previewUrl);
      isUploadedObservable.subscribe((isUploaded: boolean) => {
        this.isUploading = false;
        this.isUploaded = isUploaded;
        if (this.isUploaded) {
          setTimeout(() => this.router.navigate(['/']), 500);
        }
      });
    }
  }
}

<main class="w-screen min-h-screen flex flex-col">
  <app-header />
  <div
    class="flex flex-col items-center w-[90%] min-h-[75dvh] bg-white text-black font-roboto rounded-2xl pb-10 space-y-10 self-center"
  >
    <div class="flex flex-col w-[90%] space-y-10 mt-10">
      <p class="font-bold text-3xl text-nowrap max-sm:text-xl">
        Dodawanie zdjęcia
      </p>
      <p class="font-extralight text-lg text-justify">
        Wybierz lub upuść zdjęcie aby automatycznie je dodać na forum!
      </p>
    </div>
    <div
      class="flex flex-col w-[90%] items-center justify-center border-black border-dashed border-2 rounded-2xl p-20 min-h-[55dvh] transition-all duration-300"
      [ngClass]="{
        'bg-[#d9d9d9] hover:bg-[#a3a3a3]': !previewUrl,
        'bg-cover bg-center': previewUrl
      }"
      [ngStyle]="
        previewUrl ? { 'background-image': 'url(' + previewUrl + ')' } : {}
      "
      (dragover)="onDragOver($event)"
      (drop)="onDrop($event)"
    >
      <div
        class="flex flex-col items-center justify-center"
        [ngClass]="{ 'bg-black bg-opacity-50 p-5 rounded-lg': previewUrl }"
      >
        <app-image
          *ngIf="!isUploading && !previewUrl"
          imageAlt="cloud"
          imageName="cloud.png"
          renderingMethod="client"
          imageClass="my-10"
          dotsClass="h-4 w-4 rounded-sm bg-[#fdd458]"
        />
        <div
          *ngIf="isUploading"
          class="animate-spin rounded-full h-16 w-16 border-t-4 border-b-4 border-white my-10"
        ></div>
        <div *ngIf="isUploaded === false" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-md mb-4 text-center">
          <p><strong>Błąd!</strong> Nie udało się dodać zdjęcia. Spróbuj ponownie.</p>
        </div>
        <div *ngIf="isUploaded === true" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded-md mb-4 text-center">
          <p><strong>Sukces!</strong> Zdjęcie zostało dodane pomyślnie.</p>
        </div>
        <p
          class="text-center font-light text-nowrap mb-5"
          [ngClass]="{ 'text-white': previewUrl }"
        >
          {{
            previewUrl
              ? "Zdjęcie zostało wybrane"
              : "Upuść zdjęcie lub kliknij tutaj"
          }}
        </p>
        <input
          type="file"
          accept="image/*"
          class="hidden"
          #fileInput
          (change)="onFileSelected($event)"
        />
        <button
          class="mt-4 px-4 py-2 bg-black text-white hover:bg-gray-500 text-nowrap rounded-lg drop-shadow-lg flex flex-row"
          (click)="fileInput.click()"
          [disabled]="isUploading"
          [ngClass]="{ 'opacity-50 cursor-not-allowed': isUploading }"
        >
          <app-image
            imageAlt="photo add icon"
            imageName="photo-add.png"
            renderingMethod="client"
            imageClass="pr-2 pt-1"
            dotsClass="h-4 w-4 rounded-sm bg-[#fdd458]"
          />
          {{ previewUrl ? "Zmień zdjęcie" : "Wybierz zdjęcie" }}
        </button>
      </div>
    </div>
  </div>
  <app-footer />
</main>

// frontend - next.js/app/add-photo/page.tsx
"use client";

import { useIsAuthorizedQuery } from "@/hooks/queries/is-authorized.query";
import { unauthorized } from "next/navigation";
import { CloudDownload } from "lucide-react";
import Image from "next/image";
import { useState } from "react";
import { toast } from "react-toastify";
import axiosInstance from "@/interceptor";
import { useUploadPhotoMutation } from "@/hooks/mutations/upload-photo.mutation";

export default function AddPhotoPage() {
  const { data: isAuthorized } = useIsAuthorizedQuery();

  if (isAuthorized === false) {
    unauthorized();
  }

  const uploadPhotoMutation = useUploadPhotoMutation();

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    const file = event.dataTransfer.files[0];
    if (file && file.type.startsWith("image/")) {
      setSelectedFile(file);
      setPreview(URL.createObjectURL(file));
    }
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && file.type.startsWith("image/")) {
      setSelectedFile(file);
      setPreview(URL.createObjectURL(file));
    }
  };

  const handleUpload = async () => {
    if (!selectedFile) return;

    setIsUploading(true);

    try {
      const reader = new FileReader();
      reader.onload = async () => {
        const base64Image = reader.result?.toString();
        if (!base64Image) {
          throw new Error("Failed to read the file.");
        }

        const payload = {
          path: base64Image,
        };

        await uploadPhotoMutation.mutateAsync(payload);

        toast.success("Zdjęcie zostało dodane pomyślnie!");

        setSelectedFile(null);
        setPreview(null);
      };

      reader.readAsDataURL(selectedFile);
    } catch (error) {
      console.error("Error uploading photo:", error);
      alert(
        error instanceof Error
          ? error.message
          : "An error occurred while uploading the photo."
      );
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-lg md:max-w-xl">
        <h1 className="text-2xl md:text-3xl font-bold text-gray-800 mb-2">
          Dodawanie zdjęcia
        </h1>
        <p className="text-gray-600 text-sm md:text-base mb-6">
          Wybierz lub upuść zdjęcie aby automatycznie dodać je do forum!
        </p>

        <div
          className="border-2 border-dashed border-gray-300 rounded-lg p-6 md:p-8 text-center flex flex-col items-center justify-center h-48 md:h-64"
          onDrop={handleDrop}
          onDragOver={(e) => e.preventDefault()}
        >
          {preview ? (
            <Image
              src={preview}
              alt="Preview"
              className="object-contain h-full w-full"
              width={200}
              height={200}
            />
          ) : (
            <>
              <CloudDownload className="w-12 h-12 md:w-16 md:h-16 text-gray-600 mb-4" />
              <p className="text-gray-500 text-sm md:text-base">
                Upuść zdjęcie lub kliknij tutaj
              </p>
            </>
          )}
          <input
            type="file"
            accept="image/*"
            className="hidden"
            id="fileInput"
            onChange={handleFileChange}
          />
          <label
            htmlFor="fileInput"
            className="cursor-pointer text-blue-500 underline mt-2"
          >
            Wybierz plik
          </label>
        </div>

        <button
          className="mt-6 w-full bg-gray-800 text-white py-2 md:py-3 rounded-lg hover:bg-gray-700 transition-colors flex items-center justify-center gap-2"
          onClick={handleUpload}
          disabled={isUploading || !selectedFile}
        >
          {isUploading ? "Wgrywanie..." : "Dodaj zdjęcie do forum"}
        </button>
      </div>
    </div>
  );
}
